meta_product_name: "Calypso"
meta_title: "Calypso - The surftrip community"
meta_description: "Join a surftrip, it has never been so easy !"
meta_image: cl_image_tag("ss5f6pi0md3jk8wvptvp.jpg")                         # Une image dans votre dossier app/assets/images/
