meta_product_name: "Calypso"
meta_title: "Calypso - The surftrip community"
meta_description: "Join a surftrip, it has never been so easy !"
meta_image: "meta-picture.jpeg"                           # Une image dans votre dossier app/assets/images/
